version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - misspell
    - unconvert
    - unparam

linters-settings:
  govet:
    enable-all: true

