version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - misspell
    - unconvert
    - unparam

linters-settings:
  govet:
    enable-all: true

